#!/bin/bash

# This bash script installs the pdf2htmlEX laminar job scripts

source ../laminar-scripts/laminar.conf

binDir=$HOME/bin

jobDir=$LAMINAR_HOME/cfg/jobs

cp bin/startLaminarPdf2htmlEX $binDir

cp jobs/pdf2htmlex*           $jobDir
