#!/bin/bash

# This bash script installs the pdf2htmlEX laminar job scripts

source ../laminar-scripts/laminar.conf

binDir=$HOME/bin

jobDir=$LAMINAR_HOME/cfg/jobs

cp bin/startLaminarPdf2htmlEX $binDir

cp jobs/buildPdf2htmlEX.run        $jobDir
cp jobs/testPdf2htmlEX.run         $jobDir
cp jobs/testPdf2htmlEXAppImage.run $jobDir
cp jobs/testPdf2htmlEXDpkg.run     $jobDir
cp jobs/testPdf2htmlEXDocker.run   $jobDir
