#!/bin/bash

# This bash script installs the pdf2htmlEX laminar job scripts

source ../laminar-scripts/laminar.conf

binDir=$HOME/bin

jobDir=$LAMINAR_HOME/cfg/jobs

tarDir=$LAMINAR_HOME/cfg/tarArchives
mkdir -p $tarDir

cp bin/startLaminar*  $binDir

cp bin/checkLaminar*   $binDir

cp bin/uploadLaminar*  $binDir

cp jobs/pdf2htmlex*    $jobDir

cp tarArchives/pdf2htmlEX-examples-*.tar.gz $tarDir/pdf2htmlEX-examples.tar.gz
